### ISSUE TITLE
IOU-Net application to other network.

### ISSUE THREAD

**Issue by IlchaeJung** [visionml/pytracking#109]
Hi, I appreciate your public release of this tracking package.
I am very interested in this trackers and try to make meaningful experience with it.

Actually, I have some questions with the possibility of IOU-Net application.
If you have an experience with my questions, could you give me some hints?

1. first of all, is IOU-Net applicable to shallow network(e.q. VGG-M / ALEXNET) ?
    or do you have experiences on other networks?
2. I saw that precise ROI Pooling is critical to train IOU-Net on original paper. But, I think that roi-align layer is still currently powerful for almost all computer vision tasks and prPOOL is miner method compared to roi-align. My real curiosity is that is IOU-Net with roi-align not competitive?
 
Thank you!

**Comment by martin-danelljan** [comment]
Hi. Thanks.

1. Yes it should be perfectly applicable, but I have not tried it.
2. Precise ROI pool is essentially the same as ROI align, with only one crucial difference: prPool is **differentiable w.r.t. the region coordinates**, which is important during inference in order to maximize the IoU. Please see our ATOM paper for details.

Regards,
Martin
