### ISSUE TITLE
UAV123 dataset process

### ISSUE THREAD

**Issue by songdejia** [visionml/pytracking#119]
we download uav123 but only 91 videos found, 
can i ask how to process?

**Comment by goutamgmb** [comment]
Yes, uav123 contains only 91 videos. However some of them are split into smaller videos to get a total of 123 test sequences. If you check the annotation folder, you will find annotation for all 123 sequences. 

In order to evaluate on uav123 using pytracking, you should have the following directory structure:

uav123_root
---- anno
-------- UAV123
------------ bike1.txt
------------ bike2.txt
------------ .... (all 123 annotation files)
---- data_seq
-------- UAV123
------------ bike1
------------ bike2
------------ .....(all 91 videos)
