### ISSUE TITLE
About ONNX support

### ISSUE THREAD

**Issue by Enlistedman** [visionml/pytracking#126]
Hello,thanks for your nice work! I want to convert the atom-model to  the onnx-model.Can you give me some suggestions ?Sincerely~

**Comment by martin-danelljan** [comment]
Hi. This would could be difficult if you want to export the IoU-Net part of the network since it uses the [PrROIPooling](https://github.com/vacancy/PreciseRoIPooling). Such a module could be implemented in plain PyTorch, but it would be quite slow. I dont know of any other implementations of this layer.

Regards,
Martin
