### ISSUE TITLE
Dimp analysis

### ISSUE THREAD

**Issue by shah0nawaz** [visionml/pytracking#161]
HI sir,
1. Using run_tracker.py I have evaluated the dimp50 tracker on VOT 2018 dataset. which saved the results in the tracking_results folder with file names such as ants1.txt and ants1_time.txt. Now I want to analyze the model so that 
     1. I can find out the Robustness and Accuracy values on this data set. Please help me how can I   do this.

     2. If I want to evaluate these models on my own custom data set, then how can I prepare my own  datasets in a standard way.

Thanks in advance

**Comment by EraProphet** [comment]
> HI sir,
> 
> 1. Using run_tracker.py I have evaluated the dimp50 tracker on VOT 2018 dataset. which saved the results in the tracking_results folder with file names such as ants1.txt and ants1_time.txt. Now I want to analyze the model so that
>    
>    1. I can find out the Robustness and Accuracy values on this data set. Please help me how can I   do this.
>    2. If I want to evaluate these models on my own custom data set, then how can I prepare my own  datasets in a standard way.
> 
> Thanks in advance

hi,i encounter the same question and i don't solve it , have you solved it ？ please help me, appreciation

**Comment by goutamgmb** [comment]
Hi,

You will have to use the official VOT 2018 toolkits to compute the robustness and accuracy scores.

In order to evaluate on your custom data, you can check any of the existing dataset files e.g. [otbdataset.py](https://github.com/visionml/pytracking/blob/master/pytracking/evaluation/otbdataset.py) in order to see how to create a dataset class for your custom data.
