### ISSUE TITLE
The results of SuperDimp.

### ISSUE THREAD

**Issue by iminfine** [visionml/pytracking#162]
Could you please provide the results of SuperDimp? 

I can't reproduce the results on UAV123. I run it multi times, the best AUC on UAV123 is 66.8 far from 68.1. 

and could you please also provide the parameter file of VOT2018?

**Comment by martin-danelljan** [comment]
Hi.

We will provide raw results for SuperDiMP when time allows.

The difference in SuperDiMP results is just due to differences in evaluation strategies as [explained here](https://github.com/visionml/pytracking/issues/87#issuecomment-619373519). We changed our evaluation code to reflect the UAV toolkit computation instead of the OTB protocol, so your results are correct. But we did not update the table in the ModelZoo (sorry for that).

We have not experimented with SuperDiMP and VOT2018. I would suggest starting from the DiMP50 VOT settings and integrate the SuperDiMP model and bounding box parameters.

**Comment by iminfine** [comment]
Thank I will try.
