### ISSUE TITLE
about the fourier code

### ISSUE THREAD

**Issue by kuiran** [visionml/pytracking#184]
![image](https://user-images.githubusercontent.com/25083462/93883413-1b744780-fd14-11ea-82a5-68c0ad59b720.png)
 i'm confused about this code, i think i is a reverse operation of  irfftshift2 , but it's not. It is (h-1)//2 not h//2,could you tell me why use (h-1)//2, i try h//2, it seems not different performence on vot2018.
On the other hand, i can't fully understand the process about the scores_raw to get score_map, could you tell me what paper or book will help me?Thank you and hope to get your reply.

**Comment by martin-danelljan** [comment]
This should basically correspond to the fftshift/ifftshift operations in matlab. But you are right that if the shape changes if the size is even. I think I intentionally wrote it like this in order to have an odd number of Fourier coefficients. There is also a possibility of a bug. But it was such a long back I wrote this, so I would need really dig into it again :P
