### ISSUE TITLE
Exception: No mask provided

### ISSUE THREAD

**Issue by devendraswamy** [visionml/pytracking#187]
python ./pytracking/run_video.py lwl lwl_ytvos /media/dell/475E5B7F1FA6CE1E/Devendra/Tracking/siamban/results/video8/video5.mp4 --debug 1 --save_results 

File "/media/dell/475E5B7F1FA6CE1E/Devendra/Tracking/pytracking/pytracking/tracker/lwl/lwl.py", line 84, in initialize
    raise Exception('No mask provided')# here the pblm
Exception: No mask provided

please help me , Thank you

**Comment by Kouin** [comment]
Hello, you should initial weight using ‘lwl_boxinit’ parameters' file with relevent weight--'lwl_boxinit.pth', which could enables you to initial mask with manual interaction. Otherwise, mask should be init in other way(i dont know which...) as there are not masks provided when you pause in debug mode.

**Comment by goutamgmb** [comment]
Yes, as pointed out by @Kouin you can use the 'lwl_boxinit' parameter setting to perform VOS with box input.
