### ISSUE TITLE
The expanded size of the tensor (72) must match the existing size (18) at non-singleton dimension 1.  Target sizes: [72, 72].  Tensor sizes: [18, 18]

### ISSUE THREAD

**Issue by antdimarino** [visionml/pytracking#202]
Hello,
I tried to train ATOM by replacing the backbone with one trained by me. 
I tried running this command after training: 
`python run_tracker.py atom default --dataset_name vot --sequence basketball --threads 2`

And during execution I receive this error:
`The expanded size of the tensor (72) must match the existing size (18) at non-singleton dimension 1.  Target sizes: [72, 72].  Tensor sizes: [18, 18]`

This error appears while performing this function:
[https://github.com/visionml/pytracking/blob/master/pytracking/tracker/atom/atom.py#L566](url)

Could you help me solve it?
The backbone I trained is a resnet with odeblock, so it respects the layer sizes that were there before. 

If you need more information let me know.

Also I would like to compliment you on your work which is really interesting.

**Comment by goutamgmb** [comment]
Hi,

Sorry for the late response. It is possible that the tracker is using the wrong feature block due to some mis-match in the naming. It would be hard to help without more information/code. I would suggest using a debugger, e.g. on Pycharm to check which feature block is actually being used for tracking.
