### ISSUE TITLE
Confusion about testing

### ISSUE THREAD

**Issue by FadedFate** [visionml/pytracking#212]
Hey there, I notice there are some scripts to evaluate tracker's performance in pytracking lib, such as run_tracker.py or run_experiment.py. Through that, I can get the result evaluating on the other datasets like OTB\VOT\UAV.

> `python run_experiment.py experiment_module experiment_name --dataset_name dataset_name --sequence sequence  --debug debug --threads threads`

However, I am quite confused whether I am supposed to directly use that result for further evaluation? Did you use the official evaluation toolkit like OTB / Lasot toolkit to get the final evaluation?

I am confused because I think VOT has a restart mechanism that the tracker will be re-initialized after failure, but I cannot find the corresponding code in pytracking file folder. So, 
1. Do I have to use the vot-toolkit to get the VOT2018 testing result ?
2. And is there some problem for those other OPE dataset testing (OTB/LASOT/...), where I just use the script to get the testing result and use that result for further evaluation ?

Did I miss something? Look forward to any help, thanks.

**Comment by goutamgmb** [comment]
Hi,

The run_experiment script will run the trackers on the given datasets, and save the results. In order to compute the performance scores, e.g. AUC curves, OP scores, you can use the analysis module in pytracking. Check the notebook https://github.com/visionml/pytracking/blob/master/pytracking/notebooks/analyze_results.ipynb which provides examples of using the analysis module.

Regarding VOT, yes you will have to use the official VOT toolkits to compute the EAO score. 

Regards
Goutam

**Comment by FadedFate** [comment]
OK, that helps a lot.
Thanks for your reply.
