### ISSUE TITLE
stochastic nature

### ISSUE THREAD

**Issue by zlj199502** [visionml/pytracking#22]
Hi
What is the stochastic nature of the tracker affected by?

**Comment by martin-danelljan** [comment]
Hi,
We do some random dropout and shifts in the data augmentation. Also the refinement of the bounding box is stochastic since we use random initializations.

Regards,
Martin

**Comment by zlj199502** [comment]
Thanks for your reply. The results of my test fluctuated greatly on VOT2018, which was about 0.05. Is there any way to reduce this fluctuation?

**Comment by goutamgmb** [comment]
Hi,

We have encountered similar behavior on VOT for a single run of the tracker. Unfortunately, there is no way to reduce the fluctuations. We believe the fluctuations are due to the small size of the dataset. Thus, it is important to average the results over multiple runs (we used 15 runs, as recommended by VOT guidelines) to obtain a stable performance estimate.
