### ISSUE TITLE
Two requests about the released results

### ISSUE THREAD

**Issue by fzh0917** [visionml/pytracking#222]
Hi, @martin-danelljan  and @goutamgmb, thank you for your recent excellent works such as ATOM, (Pr)DiMP, KYS, .etc.
Would you please:
* provide sole results instead of 5 runs of all trackers? We hope that the sole results should be the same as or similar to those reported in the original papers.
* organize result files by dataset names?

Your efforts are very meaningful for all researchers to plot AUC figures, visualize results, .etc.
Thank you very much. ❤️👍

**Comment by goutamgmb** [comment]
Thanks you for your kind words.

Unfortunately it is not possible to provide a single result for these trackers since we take the average of the AUC curves. Note that you can use our analysis package to obtain the average AUC curve. In case you want to use an external evaluation toolkit, you could use the run which obtains the median AUC score. This will give you similar, but not exact scores, compared to those reported in the papers. 

We provide results organized by dataset names for GOT-10k, TrackingNet, and VOT2018 dataset [here](https://drive.google.com/drive/folders/1WiUpRwPcOFTVYaEkW7lj-Ok3zFPV_OXB). For other datasets, we organize the results so that our analysis package can be directly employed to compute performance scores. In case you want to use an external toolkit, it should be easy to write scripts which can move/rename the result files accordingly. Since different toolkits can have different ways of organizing result files, it is not possible to organize the result files in such a way that it is compatible with all toolkits. Thus, we do not plan release any scripts for converting our results, or re-organize the results files.

Regards
Goutam

**Comment by fzh0917** [comment]
Okay, got it. Thank you very much.
