### ISSUE TITLE
How can I speed up DimpNet with Nvidia tensorRT developer?

### ISSUE THREAD

**Issue by twilight-09** [visionml/pytracking#239]
Hi!

Thank you for these amazing works.

I am trying to speed up DimpNet with Nvidia tensorRT developer by using torch2trt converter. However,  the forward function of DimpNet is only used for training, torch2trt converter can not run through the forward function.

I have tried to only convert DimpNet.feature_extractor( it should be resnet18 when I using dimp18, right?) to tensorRT, but it failed too. 

Could you give some advices? Appreciate for your help!

**Comment by martin-danelljan** [comment]
Hi. 

Thank you for raising this issue. As you say, we are often using the convention of calling `forward` for training and only use the needed methods defined in the network during inference. We have noticed that this is contrary to some libraries which assumes that `forward` is the inference function. (we will consider this for future refactoring)

The point is that in our tracker we are calling different parts of the network at different occasions, due to the nature of the problem. So it is difficult to put everything in one forward function while maintaining flexibility. Right now I have no simple solution for you. You can go through the tracker function and try to put the most important functions into a single forward pass. It would require quite some refactoring though.

Just converting the feature extractor is a better choice as you tried. Not sure why you would get an error there.

**Comment by twilight-09** [comment]
Appreciate for your reply! 

I have tried to convert dimp18's backbone resnet18 to tensorRT in dimpnet.py, after line108, backbone_net = backbones.resnet18(..). When I tried model = backbone_net.eval(), it returns nothing. It seems like the train() function in pytrakcing/ltr/models/backbone/base.py lost return value? The super() function of train() in /torch/nn/modules/module.py "return self " in the end of the function. Is "return self" not needed in train() of base.py?

Best Wishes!

**Comment by martin-danelljan** [comment]
Your are right. I pushed a fix for this just now :) Thanks!

**Comment by twilight-09** [comment]
It's my pleasure to help you!
Looking forward for your new tracker!

**Comment by mj8ac** [comment]
> It's my pleasure to help you! Looking forward to your new tracker!

Have you managed to accelerate this using TensorRT? We are also working on an implementation but what to try and export the model from pytorch to onnx and then from onnx to tensorRT. 

We are having issues exporting to onnx right now.

**Comment by Zalways** [comment]
have you succeed in exporting the onnx version model? i also want to convert the model to onnx, so that i can inference with c++.
@mj8ac @twilight-09
