### ISSUE TITLE
Pick up models to run on edge devices, is it possible?

### ISSUE THREAD

**Issue by franva** [visionml/pytracking#279]
Hi there,

Thanks for sharing this great code to the public.

I had a try and the code works amazing~!!!

Is it possible to run any model in model zoo on an edge device?

I have OAK-D camera from OpenCV which integrates an Intel Movidius Myriad X VPU.

If the above hardware is not supported, what model could be run on a RPi 4 with 4GB RAM?

I hope there would be some models which is small enough to run on edge devices which is a huge bonus ~!

Looking forward to any answers or suggestions.

**Comment by 2006pmach** [comment]
Not sure about that, but I doubt that the code runs on an RPI 4 or an Intel Movidius Myriad X VPU because the bounding box regression module (PrRoiPooling) requires CUDA and therefore a Nvidia graphics card. Maybe a Nvidia Jetson could work but never tried that. For sure I would select a tracker with resnet18 backbone to keep it small and fast. You could try PrDiMP-18 but as I said it needs CUDA support. Maybe @goutamgmb has an idea or insights what could work for you.

**Comment by 2006pmach** [comment]
You could have a look here maybe this helps https://github.com/visionml/pytracking/issues/255

**Comment by franva** [comment]
thanks, I will have a look and give a try. Finger cross
