### ISSUE TITLE
Preformance on pre-traind model

### ISSUE THREAD

**Issue by huanmx** [visionml/pytracking#296]
Hi! 
Thank for your great work!

I used the pre-trained ATOM model and tested on the UAV123 dataset. I got 62.0 AUC score(average of 5 runs) which is lower than the given raw results(63.2 AUC score). Does this performance normal? How can I get the correct results.

Thank you for your time.

**Comment by 2006pmach** [comment]
Hi, did you try downloading the provided results and could you reproduce the performance reported in this repository (63.2)? This is just a check to make sure that your eval setup is correct. Otherwise have a look a the individual runs on UAV123 instead of averaging over 5. What do you get? In the end the tracker is stochastic and it might be that you get lower results than specified sometimes due to this.

**Comment by huanmx** [comment]
> Hi, did you try downloading the provided results and could you reproduce the performance reported in this repository (63.2)? This is just a check to make sure that your eval setup is correct. Otherwise have a look a the individual runs on UAV123 instead of averaging over 5. What do you get? In the end the tracker is stochastic and it might be that you get lower results than specified sometimes due to this.

I have tried to use the given raw results and got the performance reported in this repository (63.2 AUC score). The individual runs(62.8) on UAV123 is also lower than the raw results(64.3) with the same runid 0. The same performance appears in other model, which is lower than the raw results.

**Comment by 2006pmach** [comment]
you can try all runids from 0 to 5 to get the individual runs and check the distribution. In the end it could be that your results are lower due to the stochasticity in training and inference. You could try to retrain the model and check again if needed. Overall I don't think that there is a problem with your setup. I think that your reported results are within the expected range.

**Comment by ardamamur** [comment]
> UAV123
Hi haunmx,
I am trying to train a pretrained model with UAV123 dataset too for my final thesis. It would be grate if you can share the steps or the code about how to process UAV123 dataset with pretrained models. 
My email: arda.burak.mamur@gmail.com
