### ISSUE TITLE
Correction needed in pytracking/parameter/dimp folder

### ISSUE THREAD

**Issue by Ahsanr312** [visionml/pytracking#305]
@martin-danelljan 
prdimp18.py, prdimp50.py, prdimp50_vot18.py, super_dimp.py

All the above mentioned files call .pth.tar file in 
params.net = NetWithBackbone

Whereas the weights downloaded are just .pth extension
Changing this to .pth only runs all the above models and same goes for all other folders

**Comment by 2006pmach** [comment]
Not sure what the problem is. You are right, the shared models for dimp follow the `*.pth` convention whereas the prdimp and superdimp models follow the `*.pth.tar` convention. I agree that this is not consistent but as far as I can see the file extensions in the parameter files and the uploaded checkpoint files agree so this shouldn't cause any problems and run as expected.
