### ISSUE TITLE
Track doesn't loose

### ISSUE THREAD

**Issue by Ahsanr312** [visionml/pytracking#318]
Hello @2006pmach ,

I have noticed a problem while using Dimp18 tracker. Even the object is not in the scene for a small or long time it remains the Bounding Box (track) on something during the video or a stream. 

Secondly, can you please explain is the classification is running on whole frame or a specific patch during the tracking. 

How to solve this problem, have you noticed this issue ?

**Comment by 2006pmach** [comment]
Hey 

I am not entirely sure what scenario you mean but I can say the following.

Generic object tracking is still an open research topic and many problems remain. While we see better and better trackers being developed non is perfect and they fail in challenging scenarios. So yes it is true that DiMP and other trackers fail from time to time and start to track a distractor instead of the target. This even happens for KeepTrack however much less frequently than for DiMP18. But yes in general it is often difficult for trackers to detect occlusions or out-of-view reliably and to re-detect the target once it becomes visible again.

If you are asking why the tracker produces a bounding box for cases where we detect the absence of the target (maximum value in the score map is bellow a threshold). Then the answer is simply that we report the bounding box belonging to the most recent frame where we detect the target and output it for the current frame. This behaviour is partly motivated by the different benchmarks and how they compute the performance metrics (oxuva, lasot etc). Anyway, in case you prefer that no bounding box is displayed for this cases you can simply remove or ignore it when the max value of the score map is bellow the threshold.
