### ISSUE TITLE
Excuse me: if the confidence of the detected target is low, I want the bounding box not to be displayed. Where can I adjust this threshold.

### ISSUE THREAD

**Issue by Shengstudy** [visionml/pytracking#319]
Excuse me: if the confidence of the detected target is low, I want the bounding box not to be displayed. Where can I adjust this threshold.

**Comment by 2006pmach** [comment]
So for DiMP there is [this](https://github.com/visionml/pytracking/blob/3e6a8980db7a2275252abcc398ed0c2494f0ceab/pytracking/tracker/dimp/dimp.py#L119) function that is called within the `track()` function that returns the `flag` variable. One state is `not_found` which corresponds typically to the situation when the following holds `score_map.max() < self.params.target_not_found_threshold` the `target_not_found_threshold` is something like `0.25` depending on the parameter file that you use. 
Now in the track function there is [this line](https://github.com/visionml/pytracking/blob/3e6a8980db7a2275252abcc398ed0c2494f0ceab/pytracking/tracker/dimp/dimp.py#L169) that basically returns the `[-1,-1,-1,-1]` dummy box if the target was not found and `self.params.output_not_found_box=True` is specified in the parameter file. So you can either return this bounding box or whatever you like if the `flag` variable is set to `not_found`. If you want to alter the visualization shown in visdom check [here](https://github.com/visionml/pytracking/blob/3e6a8980db7a2275252abcc398ed0c2494f0ceab/pytracking/tracker/dimp/dimp.py#L861) otherwise you can find the `[-1,-1,-1,-1]` representation the produced txt files storing the bounding box that indicates that the target was not found.

**Comment by Ahsanr312** [comment]
I have read your comment with focus but can you direct me to the python file where this track () function is called. 
I also want to make the above changes but unable to find the right place to do it.

Thanks

**Comment by 2006pmach** [comment]
Just click on the links an you are there?

**Comment by 2006pmach** [comment]
The `track` method is for example called [here](https://github.com/visionml/pytracking/blob/3e6a8980db7a2275252abcc398ed0c2494f0ceab/pytracking/evaluation/tracker.py#L216).

**Comment by Ahsanr312** [comment]
And where to make the above changes ? Is it here by adding like this

        if flag != 'not_found':
            if self.params.get('use_iou_net', True):
                update_scale_flag = self.params.get('update_scale_when_uncertain', True) or flag != 'uncertain'
                if self.params.get('use_classifier', True):
                    self.update_state(new_pos)
                self.refine_target_box(backbone_feat, sample_pos[scale_ind,:], sample_scales[scale_ind], scale_ind, update_scale_flag)
            elif self.params.get('use_classifier', True):
                self.update_state(new_pos, sample_scales[scale_ind])
        elif flag == 'not_found':
            output_state = [-1, -1, -1, -1]

**Comment by 2006pmach** [comment]
I am happy to give some guidance as above but I won't check and correct your custom modifications. Please test this yourself.

**Comment by Ahsanr312** [comment]
Okay and thankyou for your response. Much appreciate your efforts.

**Comment by Ahsanr312** [comment]
Just to add here as a reference, one need to change only one thing nothing else and that is in track () function. Just change this False to True.

        if self.params.get('output_not_found_box', False) and flag == 'not_found':
            output_state = [-1, -1, -1, -1]
        else:
            output_state = new_state.tolist()

        out = {'target_bbox': output_state}
        return out

**Comment by Shengstudy** [comment]
@2006pmach I have solved the problem with your guidance,thank you very much,my english is not very good ,thank you again!

**Comment by Shengstudy** [comment]
@Ahsanr312  yes!perfectly right！
