### ISSUE TITLE
RTS Tracker Prediction Score

### ISSUE THREAD

**Issue by eliafranc** [visionml/pytracking#426]
Hey,

I was wondering if it is possible to get the bounding box / segmentation prediction score for the RTS tracker somehow? I checked the output from the .track() function and it seems the output includes the following: `['segmentation', 'segmentation_raw', 'target_bbox', 'time']` but no prediction score.

I am looking to get the prediction score as I am looking into evaluating some data with the COCO mAP metric. 

EDIT:
I did manage to find a classifier score in the [classifier branch](https://github.com/visionml/pytracking/blob/master/pytracking/tracker/rts/clf_branch.py) class, inside the update_state(...) function. This score is also titled 'DiMP Max score'. However the score sometimes is a little more than 1.0. Do I just use a sigmoid on the DiMP Max score in order to get a prediction score?

Thanks!

**Comment by 2006pmach** [comment]
The classification scores in DiMP can be smaller than 0 or larger than 1. Since we are not enforcing any limits here but rather compute a hinge like loss between the ground truth score map [0,1] and the predictions. Since we mainly care about localizing the object in the scene (locations > threshold) negative values or values above 1 are not an issue for our task. You can certainly squeeze these score values in the [0,1] interval by clipping or using a sigmoid. Depends what works for you. For the segmentation mask you get probability values for each location in the output. It is up to you to define a classification score based on the raw segmentation values that fits your need.
