### ISSUE TITLE
Pooled features with the coefficient vector

### ISSUE THREAD

**Issue by caimingxie** [visionml/pytracking#51]
Hi:
              Thank yours work. Recently when read ATOM paper and code, the sentence in the paper at Figure3,   "The pooled features are modulated by channel-wise multiplication with the coefficient vector returned by the reference branch." In the file atom_iou_net.py,  the features before PrPool layers are modulated with coefficient vector, instead of the features after PrPool layers. The code show in below picture at red rectangle. Whether I misunderstood it?
![Screenshot from 2019-07-20 18-56-05](https://user-images.githubusercontent.com/37770769/61578163-1d95b180-ab25-11e9-9f10-8c7e80a3620b.png)

**Comment by martin-danelljan** [comment]
Hi.
In theory it does not matter if we multiply the modulation weights just before or after the pooling operation, since pooling is a linear function acting channel-wise. By doing it before pooling we obtain a slight speedup since that operation will not be in the computational graph of the IoU maximization step.

Regards,
Martin

**Comment by superkevingit** [comment]
Thanks for this issue and the reply~
