### ISSUE TITLE
Dimp and ATOM raw results on UAV different from the paper

### ISSUE THREAD

**Issue by sunhao12121** [visionml/pytracking#87]
I download the raw_result from
https://drive.google.com/drive/folders/1MdJtsgr34iJesAgL7Y_VelP8RvQm_IG_
https://drive.google.com/drive/folders/1dmy3gX7kz6kSokQZcCX4gXwxyTc_7bXK

Dimp result on UAV123:
                           success    precision
\| dimp50_000  \|  0.643  \|   0.850   \|
\| dimp50_001  \|  0.642  \|   0.849   \|
\| dimp50_002  \|  0.648  \|   0.858   \|
\| dimp50_003  \|  0.640  \|  0.847   \|
\| dimp50_004  \|  0.642  \|   0.849   \|
average is           0.643         0.8506
ATOM result on UAV123:

\| default_000 \|  0.643  \|   0.856   \|
\| default_001 \|  0.642  \|   0.854   \|
\| default_002 \|  0.633  \|   0.847   \|
\| default_003 \|  0.622  \|   0.833   \|
\| default_004 \|  0.617  \|   0.827   \|
average is        0.6314        0.8434

if it is possible that the wrong data was uploaded? thank u

**Comment by goutamgmb** [comment]
Hi,

Thanks for notifying the issue. I checked that the uploaded data is correct. The discrepancy in the results might be due to some small differences in the evaluation toolkit, although I'm not sure exactly where. We will look into it later in the month.

**Comment by goutamgmb** [comment]
Which toolkit are you using to evaluate the trackers?

**Comment by sunhao12121** [comment]
I use the toolkit from [pysot](https://github.com/STVIR/pysot/tree/master/toolkit)

**Comment by goutamgmb** [comment]
Hi,

The discrepancy in results is due to the way invalid frames are handled by the toolkit. In the UAV dataset annotations, the bounding box is set to NaN if the target is out-of-frame. The results in the paper were obtained by computing the AUC scores over only the valid frames, i.e. the frames in which the target is visible. If you compute the AUC over all frames, then you will get the score of 64.3 for DiMP-50. In either case, the ordering of the trackers will be the same, just that the scores for all trackers will be multiplied by a factor.

**Comment by Janghhy** [comment]
Hi,
have you got the same result as paper?
and,could you tell me how to use the pysot-toolkit to evaluate the atom model？
希望得到您（sunhao12121）的回复  我的邮箱是Jiangmy0813@163.com

**Comment by sunhao12121** [comment]
Thanks a lot， I see
